#!/bin/bash
echo -e "\n-----------------------------\ntest exit \n-----------------------------\n"
echo e
echo -e "\n-----------------------------\\nexpected output \n 'e' - shell shouldnt exit \n-----------------------------\\n"
echo -e "\n-----------------------------\ntest exit \n-----------------------------\n"
echo ex
echo -e "\n-----------------------------\\nexpected output \n 'ex' - shell shouldnt exit \n-----------------------------\\n"
echo -e "\n-----------------------------\ntest exit \n-----------------------------\n"
echo exi
echo -e "\n-----------------------------\\nexpected output \n 'exi' - shell shouldnt exit \n-----------------------------\\n"
echo -e "\n-----------------------------\ntest exit with arguments\n-----------------------------\n"
echo -e "\n-----------------------------\\n Please insert echo '$?' in terminal >> expected output \n 98\n-----------------------------\\n"
exit 98
echo -e "\n----END OF TEST----\n"
