#!/bin/bash
echo -e "\n-----------------------------\nTEST MKDIR\n-----------------------------\n"
mkdir test_mkdir
echo -e "\nThe folder 'test_mkdir' should be here\n"
ls
echo -e "\n-----------------------------\nTEST TOUCH\n-----------------------------\n"
touch test_touch
echo -e "\nThe file 'test_touch' should be here\n"
ls
echo -e "\n----END OF TEST----\n"