#!/bin/bash

echo -e "\n-----------------------------\ntest pwd ; ls\n-----------------------------\\n"
pwd ; ls
echo -e "\n-----------------------------\ntest ls ; ls\n-----------------------------\\n"
ls ; ls
echo -e "\n-----------------------------\ntest echo hello ; ls\n-----------------------------\\n"
echo hello ; ls
echo -e "\n-----------------------------\ntest ls- ; echo; cal\n-----------------------------\\n"
ls- ; echo; cal
echo -e "\n-----------------------------\ntest ti;me ; time\n-----------------------------\\n"
ti;me ; time
echo -e "\n-----------------------------\ntest where;is echo\n-----------------------------\\n"
where;is echo
echo -e "\n-----------------------------\ntest whereis echo ;\n-----------------------------\\n"
whereis echo ;
echo -e "\n-----------------------------\ntest cat hola; ls\n-----------------------------\\n"
cat hola ; ls
echo -e "\n-----------------------------\ntest ls ; ls -la\n-----------------------------\\n"
ls ; ls -la
echo -e "\n----END OF TEST----\n"
